worker_processes 1;

events {}

http {
    server {
        listen 80;
        server_name localhost;

        # Angular App
        root /usr/share/nginx/html;
        index index.html;

        # Prometheus Metrics
        location /metrics {
            stub_status on;
            access_log off;
            allow 127.0.0.1;
            deny all;
        }

        # Main route for the Angular app
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
