sonar.projectKey=achat-frontend-hachem-4twin9-groupe-1
sonar.projectName=achat-frontend-hachem-4twin9-groupe-1
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.login=sqa_ea2afc72f29c37abb924dd15d1e948d910e5c048
