version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: achatdb
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root"]
      interval: 5s
      timeout: 10s
      retries: 20
    networks:
      - mynetwork

  backend:
    build: ./backend
    container_name: backend-container
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true
    ports:
      - "8089:8089"
    networks:
      - mynetwork
    command: ["sh", "-c", "sleep 20 && java -jar /app.jar"]

networks:
  mynetwork:
    driver: bridge
