FROM maven:3.8.5-openjdk-17

RUN apt-get update && apt-get install -y dos2unix

WORKDIR /app

COPY . .

RUN dos2unix ./mvnw && chmod +x ./mvnw && ./mvnw clean install -DskipTests

FROM openjdk:17-jdk-slim

WORKDIR /app

COPY --from=0 /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
