server.servlet.context-path=/SpringMVC
server.port=8089

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect

# Logging configuration
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %-5level - %logger{60} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{60} - %msg%n

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect

spring.jpa.open-in-view=false

# Niveau de log
logging.level.org.springframework=DEBUG
logging.level.com.zaxxer.hikari=INFO
logging.level.tn.esprit.rh.achat.services=TRACE

logging.level.root=INFO
logging.level.tn.esprit.rh.achat=DEBUG
logging.file.name=/logs/reglement.log